### ISSUE TITLE
noVNC encounter an error

### ISSUE THREAD

**Issue by onlineapps-cloud** [kasmtech/KasmVNC#147] opened 2023-03-20 17:42 UTC
on your demo server and on my instance i receive this error:
![image](https://user-images.githubusercontent.com/69077240/226422969-70d4cd33-4345-4e46-a17b-c44a497ba863.png)

**Comment by j-travis** [comment] 2023-03-20 18:07
Duplicate of https://github.com/kasmtech/KasmVNC/issues/143

**Closed by j-travis** 2023-03-20 18:07 UTC
